//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPKIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public int IDSession { get; set; }
        public Nullable<int> IDWorker { get; set; }
        public Nullable<System.DateTime> DateSession { get; set; }
        public Nullable<System.TimeSpan> TimeSession { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
